### ISSUE TITLE
Is it deliberate that 429 errors don't count against the retryLimit?

### ISSUE THREAD

**Issue by jordanrastrick** [contentful/contentful-sdk-core#84]
Hi,

Per the subject, accidentally consuming too much of our overall API rate limits in auxiliary systems, when they come into contention for that resource with our mission critical production systems, is precisely the use case where we need more control over how many retries to attempt.

But from experimental testing and as confirmed by looking at the source code, 429 rate limit errors are just retried indefinitely. Not sure if this is a bug or by design, but it does impact on our use case - we will probably give up on attempting for fine grained control and turn retrying off completely, which is probably ok as a workaround but not ideal in the long run.

Thanks,

Jordan

**Comment by phoebeschmidt** [comment]
Hi @jordanrastrick,

This is by design. Main rationale being the import tool-- rate limit errors are expected, but we want to continue to import at all costs. Retries are meant for recovering from failure for any other reason.

I can see how this is inconvenient for your use case, but unfortunately we can't prioritize changing this at the moment. PRs are always welcome (but solutions would hopefully be compatible with an entire space import running successfully).

**Comment by jordanrastrick** [comment]
Thanks for getting back to me @phoebeschmidt . We'll weigh up our options and if there's a relatively simple solution we can address this with we may submit a PR.

**Comment by rgcunha** [comment]
Interesting, if the information above still holds then I don't understand why our content import job is failing with 429 errors explicitly. This seems to have started occurring right after we upgraded contentful-management from 7.x to 9.x which has a direct dependency on the sdk-core module. Any ideas?

The error looks like this:
```
"message\": \"You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.\",\n
```
